/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://oss.oracle.com/licenses/CDDL+GPL-1.1
 * or LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

package org.omg.CORBA;

/**
* org/omg/CORBA/ValueDefOperations.java .
* IGNORE Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlj/src/main/java/com/sun/tools/corba/ee/idl/ir.idl
* IGNORE Sunday, January 21, 2018 1:54:24 PM EST
*/

public interface ValueDefOperations  extends org.omg.CORBA.ContainerOperations, org.omg.CORBA.ContainedOperations, org.omg.CORBA.IDLTypeOperations
{

  // read/write interface
  org.omg.CORBA.InterfaceDef[] supported_interfaces ();

  // read/write interface
  void supported_interfaces (org.omg.CORBA.InterfaceDef[] newSupported_interfaces);
  org.omg.CORBA.Initializer[] initializers ();
  void initializers (org.omg.CORBA.Initializer[] newInitializers);
  org.omg.CORBA.ValueDef base_value ();
  void base_value (org.omg.CORBA.ValueDef newBase_value);
  org.omg.CORBA.ValueDef[] abstract_base_values ();
  void abstract_base_values (org.omg.CORBA.ValueDef[] newAbstract_base_values);
  boolean is_abstract ();
  void is_abstract (boolean newIs_abstract);
  boolean is_custom ();
  void is_custom (boolean newIs_custom);
  byte flags ();
  void flags (byte newFlags);

  // always 0
  boolean has_safe_base ();

  // always 0
  void has_safe_base (boolean newHas_safe_base);

  // read interface
  boolean is_a (String value_id);
  org.omg.CORBA.ValueDefPackage.FullValueDescription describe_value ();

  // write interface
  org.omg.CORBA.ValueMemberDef create_value_member (String id, String name, String version, org.omg.CORBA.IDLType type_def, short access);
  org.omg.CORBA.AttributeDef create_attribute (String id, String name, String version, org.omg.CORBA.IDLType type, org.omg.CORBA.AttributeMode mode);
  org.omg.CORBA.OperationDef create_operation (String id, String name, String version, org.omg.CORBA.IDLType result, org.omg.CORBA.OperationMode mode, org.omg.CORBA.ParameterDescription[] params, org.omg.CORBA.ExceptionDef[] exceptions, String[] contexts);
} // interface ValueDefOperations
