/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License. You can obtain
 * a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
 * or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 * Sun designates this particular file as subject to the "Classpath" exception
 * as provided by Sun in the GPL Version 2 section of the License file that
 * accompanied this code.  If applicable, add the following below the License
 * Header, with the fields enclosed by brackets [] replaced by your own
 * identifying information: "Portions Copyrighted [year]
 * [name of copyright owner]"
 *
 * Contributor(s):
 *
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_corba_se_internal_io_IIOPOutputStream */

#ifndef _Included_com_sun_corba_se_internal_io_IIOPOutputStream
#define _Included_com_sun_corba_se_internal_io_IIOPOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: subclassAudits */
/* Inaccessible static: class_00024java_00024io_00024ObjectOutputStream */
/* Inaccessible static: class_00024java_00024lang_00024Object */
#undef com_sun_corba_se_internal_io_IIOPOutputStream_kFormatVersionOne
#define com_sun_corba_se_internal_io_IIOPOutputStream_kFormatVersionOne 1L
/* Inaccessible static: class_00024java_00024io_00024IOException */
/* Inaccessible static: class_00024java_00024rmi_00024Remote */
/* Inaccessible static: class_00024org_00024omg_00024CORBA_00024Object */
/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    throwExceptionType
 * Signature: (Ljava/lang/Class;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_throwExceptionType
  (JNIEnv *, jclass, jclass, jstring);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getObjectFieldOpt
 * Signature: (Ljava/lang/Object;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getObjectFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getBooleanFieldOpt
 * Signature: (Ljava/lang/Object;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getBooleanFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getByteFieldOpt
 * Signature: (Ljava/lang/Object;J)B
 */
JNIEXPORT jbyte JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getByteFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getCharFieldOpt
 * Signature: (Ljava/lang/Object;J)C
 */
JNIEXPORT jchar JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getCharFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getShortFieldOpt
 * Signature: (Ljava/lang/Object;J)S
 */
JNIEXPORT jshort JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getShortFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getIntFieldOpt
 * Signature: (Ljava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getIntFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getLongFieldOpt
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getLongFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getFloatFieldOpt
 * Signature: (Ljava/lang/Object;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getFloatFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    getDoubleFieldOpt
 * Signature: (Ljava/lang/Object;J)D
 */
JNIEXPORT jdouble JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_getDoubleFieldOpt
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_sun_corba_se_internal_io_IIOPOutputStream
 * Method:    writeObject
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_sun_corba_se_internal_io_IIOPOutputStream_writeObject
  (JNIEnv *, jclass, jobject, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
