
/*
 * IORSystemException.java 
 * generated by mc.scm version 2.0 Sun Sep 26 16:08:23 PDT 2010
 *
 * Copyright (c) 2010 Oracle and/or its affiliates.  All rights reserved.
 *
 * Note: replace this header with the standard header.
 */

package com.sun.corba.se.impl.logging ;

import com.sun.corba.se.spi.orbutil.logex.Log ;
import com.sun.corba.se.spi.orbutil.logex.Message ;
import com.sun.corba.se.spi.orbutil.logex.LogLevel ;
import com.sun.corba.se.spi.orbutil.logex.ExceptionWrapper ;
import com.sun.corba.se.spi.orbutil.logex.WrapperGenerator ;

import com.sun.corba.se.spi.orbutil.logex.corba.ORBException ;
import com.sun.corba.se.spi.orbutil.logex.corba.CorbaExtension ;

import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.BAD_PARAM;
import org.omg.CORBA.INTERNAL;
import org.omg.CORBA.INV_OBJREF;

@ExceptionWrapper( idPrefix="IOP" )
@ORBException( omgException=false, group=CorbaExtension.IORGroup )
public interface IORSystemException {
    IORSystemException self = WrapperGenerator.makeWrapper( 
        IORSystemException.class, CorbaExtension.self ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "ObjectReferenceTemplate is not initialized" )
    INTERNAL ortNotInitialized(  ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Null POA" )
    INTERNAL nullPoa(  ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "Bad magic number {0} in ObjectKeyTemplate" )
    INTERNAL badMagic( String arg0 ) ;
    
    @Log( level=LogLevel.WARNING, id=4 )
    @Message( "Error while stringifying an object reference" )
    INTERNAL stringifyWriteError(  ) ;
    
    @Log( level=LogLevel.WARNING, id=5 )
    @Message( "Could not find a TaggedProfileTemplateFactory for id {0}" )
    INTERNAL taggedProfileTemplateFactoryNotFound( String arg0 ) ;
    
    @Log( level=LogLevel.WARNING, id=6 )
    @Message( "Found a JDK 1.3.1 patch level indicator with value {0} "
        + "less than JDK 1.3.1_01 value of 1" )
    INTERNAL invalidJdk131PatchLevel( String arg0 ) ;
    
    @Log( level=LogLevel.FINE, id=7 )
    @Message( "Exception occurred while looking for ObjectAdapter {0} "
        + "in IIOPProfileImpl.getServant" )
    INTERNAL getLocalServantFailure( String arg0 ) ;
    
    @Log( level=LogLevel.WARNING, id=8 )
    @Message( "Exception occurred while closing an IO stream object" )
    INTERNAL ioexceptionDuringStreamClose(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "Adapter ID not available" )
    BAD_OPERATION adapterIdNotAvailable(  ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Server ID not available" )
    BAD_OPERATION serverIdNotAvailable(  ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "ORB ID not available" )
    BAD_OPERATION orbIdNotAvailable(  ) ;
    
    @Log( level=LogLevel.WARNING, id=4 )
    @Message( "Object adapter ID not available" )
    BAD_OPERATION objectAdapterIdNotAvailable(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "Profiles in IOR do not all have the same Object ID, " +
        "so conversion to IORTemplateList is impossible" )
    BAD_PARAM badOidInIorTemplateList(  ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Error in reading IIOP TaggedProfile" )
    BAD_PARAM invalidTaggedProfile(  ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "Attempt to create IIOPAddress with port {0}, which is out of range" )
    BAD_PARAM badIiopAddressPort( String arg0 ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "IOR must have at least one IIOP profile" )
    INV_OBJREF iorMustHaveIiopProfile(  ) ;
}
