
/*
 * NamingSystemException.java 
 * generated by mc.scm version 2.0 Sun Sep 26 16:08:25 PDT 2010
 *
 * Copyright (c) 2010 Oracle and/or its affiliates.  All rights reserved.
 *
 * Note: replace this header with the standard header.
 */

package com.sun.corba.se.impl.logging ;

import com.sun.corba.se.spi.orbutil.logex.Log ;
import com.sun.corba.se.spi.orbutil.logex.Message ;
import com.sun.corba.se.spi.orbutil.logex.LogLevel ;
import com.sun.corba.se.spi.orbutil.logex.ExceptionWrapper ;
import com.sun.corba.se.spi.orbutil.logex.WrapperGenerator ;

import com.sun.corba.se.spi.orbutil.logex.corba.ORBException ;
import com.sun.corba.se.spi.orbutil.logex.corba.CorbaExtension ;

import org.omg.CORBA.BAD_PARAM;
import org.omg.CORBA.INITIALIZE;
import org.omg.CORBA.INTERNAL;
import org.omg.CORBA.UNKNOWN;

@ExceptionWrapper( idPrefix="IOP" )
@ORBException( omgException=false, group=CorbaExtension.NamingGroup )
public interface NamingSystemException {
    NamingSystemException self = WrapperGenerator.makeWrapper( 
        NamingSystemException.class, CorbaExtension.self ) ;
    
    @Log( level=LogLevel.WARNING, id=0 )
    @Message( "Port 0 is not a valid port in the transient name server" )
    BAD_PARAM transientNameServerBadPort(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "A null hostname is not a valid hostname in the "
        + "transient name server" )
    BAD_PARAM transientNameServerBadHost(  ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Invalid object reference passed in rebind or bind operation" )
    BAD_PARAM objectIsNull(  ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "Bad host address in -ORBInitDef" )
    BAD_PARAM insBadAddress(  ) ;
    
    @Log( level=LogLevel.WARNING, id=0 )
    @Message( "Updated context failed for bind" )
    UNKNOWN bindUpdateContextFailed(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "bind failure" )
    UNKNOWN bindFailure(  ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Resolve conversion failed" )
    UNKNOWN resolveConversionFailure(  ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "Resolve failure" )
    UNKNOWN resolveFailure(  ) ;
    
    @Log( level=LogLevel.WARNING, id=4 )
    @Message( "Unbind failure" )
    UNKNOWN unbindFailure(  ) ;
    
    @Log( level=LogLevel.WARNING, id=50 )
    @Message( "SystemException in transient name service while initializing" )
    INITIALIZE transNsCannotCreateInitialNcSys(  ) ;
    
    @Log( level=LogLevel.WARNING, id=51 )
    @Message( "Java exception in transient name service while initializing" )
    INITIALIZE transNsCannotCreateInitialNc(  ) ;
    
    @Log( level=LogLevel.WARNING, id=0 )
    @Message( "Unexpected AlreadyBound exception in rebind" )
    INTERNAL namingCtxRebindAlreadyBound(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "Unexpected AlreadyBound exception in rebind_context" )
    INTERNAL namingCtxRebindctxAlreadyBound(  ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Bad binding type in internal binding implementation" )
    INTERNAL namingCtxBadBindingtype(  ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "Object reference that is not CosNaming::NamingContext "
        + "bound as a context" )
    INTERNAL namingCtxResolveCannotNarrowToCtx(  ) ;
    
    @Log( level=LogLevel.WARNING, id=4 )
    @Message( "Error in creating POA for BindingIterator" )
    INTERNAL namingCtxBindingIteratorCreate(  ) ;
    
    @Log( level=LogLevel.WARNING, id=100 )
    @Message( "Bind implementation encountered a previous bind" )
    INTERNAL transNcBindAlreadyBound(  ) ;
    
    @Log( level=LogLevel.WARNING, id=101 )
    @Message( "list operation caught an unexpected Java exception while "
        + "creating list iterator" )
    INTERNAL transNcListGotExc(  ) ;
    
    @Log( level=LogLevel.WARNING, id=102 )
    @Message( "new_context operation caught an unexpected Java exception "
        + "creating the NewContext servant" )
    INTERNAL transNcNewctxGotExc(  ) ;
    
    @Log( level=LogLevel.WARNING, id=103 )
    @Message( "Destroy operation caught a Java exception while disconnecting from ORB" )
    INTERNAL transNcDestroyGotExc(  ) ;
    
    @Log( level=LogLevel.WARNING, id=105 )
    @Message( "Stringified object reference with unknown protocol specified" )
    INTERNAL insBadSchemeName(  ) ;
    
    @Log( level=LogLevel.WARNING, id=107 )
    @Message( "Malformed URL in -ORBInitDef" )
    INTERNAL insBadSchemeSpecificPart(  ) ;
    
    @Log( level=LogLevel.WARNING, id=108 )
    @Message( "Malformed URL in -ORBInitDef" )
    INTERNAL insOther(  ) ;
}
