
/*
 * ActivationSystemException.java 
 * generated by mc.scm version 2.0 Sun Sep 26 16:08:22 PDT 2010
 *
 * Copyright (c) 2010 Oracle and/or its affiliates.  All rights reserved.
 *
 * Note: replace this header with the standard header.
 */

package com.sun.corba.se.spi.logging ;

import com.sun.corba.se.spi.orbutil.logex.Chain;
import com.sun.corba.se.spi.orbutil.logex.Log ;
import com.sun.corba.se.spi.orbutil.logex.Message ;
import com.sun.corba.se.spi.orbutil.logex.LogLevel ;
import com.sun.corba.se.spi.orbutil.logex.ExceptionWrapper ;
import com.sun.corba.se.spi.orbutil.logex.WrapperGenerator ;

import com.sun.corba.se.spi.orbutil.logex.corba.ORBException ;
import com.sun.corba.se.spi.orbutil.logex.corba.CorbaExtension ;

import org.omg.CORBA.INITIALIZE;
import org.omg.CORBA.INTERNAL;
import org.omg.CORBA.OBJECT_NOT_EXIST;

@ExceptionWrapper( idPrefix="IOP" )
@ORBException( omgException=false, group=CorbaExtension.ActivationGroup )
public interface ActivationSystemException {
    ActivationSystemException self = WrapperGenerator.makeWrapper( 
        ActivationSystemException.class, CorbaExtension.self ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "Cannot read repository datastore" )
    INITIALIZE cannotReadRepositoryDb( @Chain Exception exc ) ;
    
    @Log( level=LogLevel.WARNING, id=2 )
    @Message( "Cannot add initial naming" )
    INITIALIZE cannotAddInitialNaming(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "Cannot write repository datastore" )
    INTERNAL cannotWriteRepositoryDb( @Chain Exception exc ) ;
    
    @Log( level=LogLevel.WARNING, id=3 )
    @Message( "Server not expected to register" )
    INTERNAL serverNotExpectedToRegister(  ) ;
    
    @Log( level=LogLevel.WARNING, id=4 )
    @Message( "Unable to start server process" )
    INTERNAL unableToStartProcess(  ) ;
    
    @Log( level=LogLevel.WARNING, id=6 )
    @Message( "Server is not running" )
    INTERNAL serverNotRunning(  ) ;
    
    @Log( level=LogLevel.WARNING, id=1 )
    @Message( "Error in BadServerIdHandler" )
    OBJECT_NOT_EXIST errorInBadServerIdHandler( @Chain Exception exc  ) ;
}
