/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright (c) 1997-2010 Oracle and/or its affiliates. All rights reserved.
 * 
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
 * or packager/legal/LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 * 
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 * 
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 * 
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

// minimal definitions to keep idltojava happy while compiling poa.idl
#pragma prefix "omg.org" 

module CORBA {   

	typedef string Identifier;
	typedef string RepositoryId;

        // basic Policy definition 
	typedef unsigned long PolicyType ;

	/** The Policy interface provides a mechanism for ORBs and Object
	* Services to allow access to certain choices that affect their 
	* operation.  This information is accessed in a structured manner
	* using interfaces derived from the org.omg.CORBA.Policy interface.
	*/
        interface Policy { 
		/** Return the constant value that corresponds to the 
		* type of the policy object.  The values of 
		* the polivy objectys are allocated by the OMG.
		* New values for PolicyType should be obtained from the OMG by
		* sending mail to request@omg.org.  In general the constant
		* values that are allocated are defined in conjunction with
		* the definition of the corresponding policy object.
		* @return the constant value that corresponds to the type of
		* the policy object.
		*/
		readonly attribute PolicyType policy_type;

		/** Copies the policy object. The copy does not retain any
		* relationships that the policy had with any domain or object.
		* @return the copy of the policy object.
		*/
                Policy copy( ); 

		/** Destroys the policy object.  It is the responsibility of
		* the policy object to determine whether it can be destroyed.
		*/
                void destroy( ); 
        }; 

        typedef sequence <Policy> PolicyList; 

	/**
	 * An interface that makes it possible to access information
	 * associated with a particular thread of execution, such as
	 * security information or a transaction identifier.
	 * <P>
	 * An ORB or CORBA service that needs its own thread-specific
	 * state extends the CORBA package's <code>Current</code>.
	 * Users of the service can obtain an instance of the appropriate
	 * <code>Current</code> interface by invoking
	 * <code>ORB.resolve_initial_references</code>.
	 * For example, the Security service obtains the <code>Current</code>
	 * relevant to it by invoking
	 * <PRE>
	 *    ORB.resolve_initial_references("SecurityCurrent");
	 * </PRE>
	 * <P>
	 * A CORBA service does not have to use this method of keeping context
	 * but may choose to do so.
	 * <P>
	 * Methods on classes that implement from <code>Current</code> access state
	 * associated with the thread in which they are invoked, not state associated
	 * with the thread from which the <code>Current</code> was obtained.
	 *  Current objects must not be exported to other processes, or externalized
	 *  with ORB.object_to_string. If any attempt is made to do so, the offending
	 *  operation will raise a MARSHAL system exception.
	 * @see <a href="package-summary.html#unimpl"><code>portable</code>
	 * package comments for unimplemented features</a>
	 */
        interface Current { };
};


