/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2002-2007 Sun Microsystems, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License. You can obtain
 * a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
 * or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 * Sun designates this particular file as subject to the "Classpath" exception
 * as provided by Sun in the GPL Version 2 section of the License file that
 * accompanied this code.  If applicable, add the following below the License
 * Header, with the fields enclosed by brackets [] replaced by your own
 * identifying information: "Portions Copyrighted [year]
 * [name of copyright owner]"
 *
 * Contributor(s):
 *
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */
package org.omg.CORBA;


/**
* The interface for <tt>Policy</tt>.  For more information on 
* Operations interfaces, see <a href="doc-files/generatedfiles.html#operations">
* "Generated Files: Operations files"</a>.
*<P>
* org/omg/CORBA/PolicyOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:20 AM PDT
*/

/**
 * Provides the operations for a <code>Policy</code> object.
 */
public interface PolicyOperations 
{

  /** 
   * Returns the constant value that corresponds to the 
   * type of the policy object.  The values of 
   * the policy objects are allocated by the OMG.
   * New values for PolicyType should be obtained from the OMG by
   * sending mail to request@omg.org.  In general the constant
   * values that are allocated are defined in conjunction with
   * the definition of the corresponding policy object.
   *
   * @return the constant value that corresponds to the type of
   * the policy object
   */
  int policy_type ();

  /** 
   * Returns a copy of the <code>Policy</code> object. The copy does not retain
   * any relationships that the policy had with any domain or object.
   *
   * @return a copy of the <code>Policy</code> object
   */
  org.omg.CORBA.Policy copy ();

  /** 
   * Destroys the <code>Policy</code> object.  It is the responsibility of
   * the <code>Policy</code> object to determine whether it can be destroyed.
   */
  void destroy ();
} // interface PolicyOperations
